kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: mfa-demo1
  annotations:
    description: Site Web qui consomme l'attestation pour les expérimentations d'une attestation délégué.
    tags: cqen, experimentation, sqin, aries, mfa, ministère de la famille, service de garde, émetteur, attestation, délégué
objects:
#MFA-wallet (PostgreSQL)
- kind: Secret
  apiVersion: v1
  metadata:
    name: mfa-wallet
    annotations:
      template.openshift.io/expose-username: "{.data['database-user']}"
      template.openshift.io/expose-password: "{.data['database-password']}"
      template.openshift.io/expose-username: "{.data['database-admin-user']}"
      template.openshift.io/expose-password: "{.data['database-admin-password']}"
      template.openshift.io/expose-password: "{.data['database-name']}"
  stringData:
    database-user: "dbuser"
    database-password: "dbpassword"
    database-admin-user: "postgres"
    database-admin-password: "dbadminpassword"
    database-name: "wallets"
- kind: Service
  apiVersion: v1
  metadata:
    name: mfa-wallet
  spec:
    ports:
    - name: mfa-wallet
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
    selector:
      name: mfa-wallet
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: mfa-wallet
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: mfa-wallet
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      app: mfa-wallet
      app.kubernetes.io/part-of: MFA
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - mfa-wallet
        from:
          kind: ImageStreamTag
          name: postgresql:10
          namespace: openshift
        lastTriggeredImage: ''
    - type: ConfigChange
    replicas: 1
    selector:
      name: mfa-wallet
    template:
      metadata:
        labels:
          name: mfa-wallet
      spec:
        containers:
        - name: mfa-wallet
          image: " "
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            exec:
              command:
              - "/usr/libexec/check-container"
          livenessProbe:
            timeoutSeconds: 10
            initialDelaySeconds: 120
            exec:
              command:
              - "/usr/libexec/check-container"
              - "--live"
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: mfa-wallet
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mfa-wallet
                key: database-password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mfa-wallet
                key: database-name
          - name: POSTGRESQL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mfa-wallet
                key: database-admin-password                
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - name: mfa-wallet-data
            mountPath: "/var/lib/pgsql/data"
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          capabilities: {}
          securityContext:
            capabilities: {}
            privileged: false
        volumes:
        - name: mfa-wallet-data
          persistentVolumeClaim:
            claimName: mfa-wallet
        restartPolicy: Always
        dnsPolicy: ClusterFirst
  status: {}

#MFA-agent
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: mfa-agent
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: mfa-agent
    name: mfa-agent
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'mfa-agent:latest'
    resources: {}
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    strategy:
      type: Docker
      dockerStrategy:
        noCache: true
        env:
          - name: POSTGRESQL_WALLET_USER
            valueFrom:
              secretKeyRef:
                name: mfa-wallet
                key: database-user
          - name: POSTGRESQL_WALLET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mfa-wallet
                key: database-password
          - name: POSTGRESQL_WALLET_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: mfa-wallet
                key: database-admin-user
          - name: POSTGRESQL_WALLET_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mfa-wallet
                key: database-admin-password
        forcePull: true
        dockerfilePath: Dockerfile
        buildArgs:
        #This is an example that we used on our demo vonx blockchain
        #Seed: 00000000000000MinistereFamilleQc
        #DID: 4nLQGUccVznQNW2Newa6Mn
        #Verkey: 34Yba1rxakA16QhYxKJyo6GepYa9Ra1yec7L5DsQHkSn
        #Alias: MFA
        - name: ISSUER_SEED
          value: 00000000000000MinistereFamilleQc
        - name: ISSUER_AGENT_ENDPOINT
          value: 'http://mfa-agent.apps.exp.lab.pocquebec.org'
        - name: ISSUER_WALLET_KEY
          value: Issuer1Wallet
        - name: ISSUER_ADMIN_API_KEY
          value: secret
        - name: ISSUER_HOSTNAME
          value: 'http://mfa-agent.apps.exp.lab.pocquebec.org'
        - name: GENESIS_URL
          value: 'http://vonx.pocquebec.org:9000/genesis'
        - name: INBOUND_PORT
          value: '8000'
        - name: API_PORT
          value: '3000'
        - name: ISSUER_POSTGRESQL_WALLET_HOST
          value: mfa-wallet
        - name: ISSUER_POSTGRESQL_WALLET_PORT
          value: '5432'
    postCommit: {}
    source:
      contextDir: MFA-agent
      type: Git
      git:
        uri: 'https://github.com/CQEN-QDCE/Demo1.git'
    triggers:
      - type: ConfigChange
    runPolicy: Serial
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: mfa-agent
    labels:
      app: mfa-agent
      app.kubernetes.io/part-of: MFA
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - mfa-agent
          from:
            kind: ImageStreamTag
            name: 'mfa-agent:latest'
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: mfa-agent
    template:
      metadata:
        labels:
          app: mfa-agent
      spec:
        containers:
          - name: mfa-agent
            image: " "
            ports:
              - containerPort: 3000
                protocol: TCP
              - containerPort: 8000
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    name: mfa-agent
  spec:
    selector:
      app: mfa-agent
    ports:
      - name: '3000'
        protocol: TCP
        port: 3000
        targetPort: 3000
      - name: '8000'
        protocol: TCP
        port: 8000
        targetPort: 8000
- kind: Route
  apiVersion: v1
  metadata:
    name: mfa-agent
  spec:
    host: mfa-agent.apps.exp.lab.pocquebec.org
    to:
      kind: Service
      name: mfa-agent
      weight: 100
    port:
      targetPort: 8000
    wildcardPolicy: None
  status:
    ingress:
      - host: mfa-agent.apps.exp.lab.pocquebec.org
        routerName: default
        conditions:
          - type: Admitted
            status: 'True'
        wildcardPolicy: None
        routerCanonicalHostname: apps.exp.lab.pocquebec.org
- kind: Route
  apiVersion: v1
  metadata:
    name: mfa-agent-admin
  spec:
    host: mfa-agent-admin.apps.exp.lab.pocquebec.org
    to:
      kind: Service
      name: mfa-agent
      weight: 100
    port:
      targetPort: 3000
    wildcardPolicy: None
  status:
    ingress:
      - host: mfa-agent-admin.apps.exp.lab.pocquebec.org
        routerName: default
        conditions:
          - type: Admitted
            status: 'True'
        wildcardPolicy: None
        routerCanonicalHostname: apps.exp.lab.pocquebec.org

#MFA-controller
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: mfa-controller
- kind: BuildConfig
  apiVersion: v1
  metadata:
    annotations:
      app.openshift.io/vcs-uri: https://github.com/CQEN-QDCE/Demo1.git
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: mfa-controller
    name: mfa-controller
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: mfa-controller:latest
    source:
      contextDir: MFA-controller
      git:
        uri: https://github.com/CQEN-QDCE/Demo1.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    triggers:
      - type: ConfigChange
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: mfa-controller
    labels:
      app: mfa-controller
      app.kubernetes.io/part-of: MFA
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - mfa-controller
          from:
            kind: ImageStreamTag
            name: "mfa-controller:latest"
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: mfa-controller
    template:
      metadata:
        labels:
          app: mfa-controller
      spec:
        containers:
          - name: mfa-controller
            image: " "
            ports:
              - containerPort: 10000
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    name: mfa-controller
  spec:
    selector:
      app: mfa-controller
    ports:
      - name: "10000"
        protocol: TCP
        port: 10000
        targetPort: 10000
- kind: Route
  apiVersion: v1
  metadata:
    name: mfa-controller
  spec:
    host: mfa-controller.apps.exp.lab.pocquebec.org
    to:
      kind: Service
      name: mfa-controller
      weight: 100
    port:
      targetPort: 10000
    wildcardPolicy: None
  status:
    ingress:
      - host: mfa-controller.apps.exp.lab.pocquebec.org
        routerName: default
        conditions:
          - type: Admitted
            status: "True"
        wildcardPolicy: None
        routerCanonicalHostname: apps.exp.lab.pocquebec.org
